spring.application.name=book-management

# Port de l'application
server.port=8080

# Configuration MongoDB
spring.mongodb.uri=mongodb://localhost:27017/library_db

# JSON formaté pour plus de lisibilité
spring.jackson.serialization.indent_output=true

# Actuator : endpoints exposés
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.mongodb.enabled=true

# Messages flash personnalisés
app.messages.book.created=✅ Livre ajouté avec succès !
app.messages.book.updated=✏️ Livre mis à jour !
app.messages.book.deleted=🗑️ Livre supprimé !

app.messages.author.created=✅ Auteur ajouté avec succès !
app.messages.author.updated=✏️ Auteur mis à jour !
app.messages.author.deleted=🗑️ Auteur supprimé !

spring.security.user.name=admin
spring.security.user.password=admin


